# https://docs.codeclimate.com/docs/advanced-configuration
version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4

  complex-logic:
    enabled: true
    config:
      threshold: 4

  file-lines:
    enabled: true
    config:
      threshold: 250

  method-complexity:
    enabled: true
    config:
      threshold: 5

  method-count:
    enabled: true
    config:
      threshold: 20

  method-lines:
    enabled: true
    config:
      threshold: 25

  nested-control-flow:
    enabled: true
    config:
      threshold: 4

  return-statements:
    enabled: true
    config:
      threshold: 4

plugins:
  # develop
  fixme:
    enabled: true

  gofmt:
    enabled: true

  golint:
    enabled: true
    
  govet:
    enabled: true

  # markdown
  markdownlint:
    enabled: true

  # shell
  shellcheck:
    enabled: true

  # legal
  git-legal:
    enabled: true

exclude_patterns:
- "eth/contract/"
